name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required by wagoid/commitlint-github-action to validate range of commits instead of just the latest one
      - uses: wagoid/commitlint-github-action@v6
        if: matrix.os == 'ubuntu-latest'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 8
          cache: maven
      - run: rm -rf /tmp/*
        if: matrix.os == 'ubuntu-latest'
        continue-on-error: true
      - name: Build with Maven
        run: mvn -ntp -U clean verify
