name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 8
          cache: maven
      - run: rm -rf /tmp/*
        if: matrix.os == 'ubuntu-latest'
        continue-on-error: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.4.0
      - name: Build with Maven
        run: |
          mvn -ntp -U clean verify -DskipTests
